# -*- coding: utf-8 -*-
"""MARL Continuous vs Discrete Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUO-1Gf4F4fhWNK5owLHVBIhgKlgq8oe
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

"""
Multi-Agent Reinforcement Learning (MARL) ODE Analyzer
------------------------------------------------------
This script uses Ljung's ODE method to analyze a 2-player, 2-action
normal-form game. It simulates discrete Cross-Learning (stochastic)
and plots it against the continuous Replicator Dynamics (deterministic ODE).
"""

class TwoPlayerGame:
    def __init__(self, payoff_A, payoff_B):
        """
        payoff_A: 2x2 numpy array representing Player 1's rewards
        payoff_B: 2x2 numpy array representing Player 2's rewards
        """
        self.payoff_A = payoff_A
        self.payoff_B = payoff_B

    def get_stochastic_reward(self, a_action, b_action, noise_std=0.1):
        """Returns the noisy reward for a specific joint action."""
        r_A = self.payoff_A[a_action, b_action] + np.random.normal(0, noise_std)
        r_B = self.payoff_B[a_action, b_action] + np.random.normal(0, noise_std)
        return r_A, r_B

def discrete_cross_learning(game, iterations, initial_alpha=0.1):
    """
    Simulates discrete, stochastic learning over time.
    State representation: (P(A plays action 0), P(B plays action 0))
    """
    # Initial policies: probability of playing action 0 (index 0)
    x = 0.5  # Player A's prob of playing action 0
    y = 0.5  # Player B's prob of playing action 0

    trajectory_x = [x]
    trajectory_y = [y]

    for n in range(1, iterations + 1):
        # 1. Robbins-Monro learning rate decay
        alpha = initial_alpha / (n ** 0.6)

        # 2. Agents sample actions based on current policy
        action_A = np.random.choice([0, 1], p=[x, 1-x])
        action_B = np.random.choice([0, 1], p=[y, 1-y])

        # 3. Observe stochastic rewards
        r_A, r_B = game.get_stochastic_reward(action_A, action_B)

        # 4. Cross-Learning Update Rules
        # If action 0 was played, push probability towards reward.
        # If action 1 was played, push probability of 0 away.
        if action_A == 0:
            x = x + alpha * r_A * (1 - x)
        else:
            x = x - alpha * r_A * x

        if action_B == 0:
            y = y + alpha * r_B * (1 - y)
        else:
            y = y - alpha * r_B * y

        # Bound probabilities strictly between 0 and 1
        x = np.clip(x, 0.001, 0.999)
        y = np.clip(y, 0.001, 0.999)

        trajectory_x.append(x)
        trajectory_y.append(y)

    return np.array(trajectory_x), np.array(trajectory_y)

def expected_vector_field(t, state, game):
    """
    The deterministic ODE equivalent (\bar{h}) derived via Ljung's Method.
    Maps exactly to asymmetric Replicator Dynamics.
    """
    x, y = state

    # Expected payoff for playing action 0 and 1 for Player A
    exp_A_0 = y * game.payoff_A[0, 0] + (1 - y) * game.payoff_A[0, 1]
    exp_A_1 = y * game.payoff_A[1, 0] + (1 - y) * game.payoff_A[1, 1]

    # Expected payoff for playing action 0 and 1 for Player B
    exp_B_0 = x * game.payoff_B[0, 0] + (1 - x) * game.payoff_B[1, 0]
    exp_B_1 = x * game.payoff_B[0, 1] + (1 - x) * game.payoff_B[1, 1]

    # Replicator Dynamics ODE formulation
    dx_dt = x * (1 - x) * (exp_A_0 - exp_A_1)
    dy_dt = y * (1 - y) * (exp_B_0 - exp_B_1)

    return [dx_dt, dy_dt]

def run_analysis():
    # Define Payoff Matrices (Matching Pennies - A zero sum game with cyclic dynamics)
    payoff_A = np.array([[1, -1],
                         [-1, 1]])
    payoff_B = np.array([[-1, 1],
                         [1, -1]])

    game = TwoPlayerGame(payoff_A, payoff_B)

    # 1. Generate the Continuous ODE Trajectories
    time_span = (0, 50)
    initial_state = [0.2, 0.3] # Start away from the (0.5, 0.5) Nash Equilibrium
    ode_solution = solve_ivp(
        expected_vector_field,
        time_span,
        initial_state,
        args=(game,),
        dense_output=True,
        max_step=0.1
    )

    # 2. Generate Vector Field Background (Phase Portrait)
    Y, X = np.mgrid[0:1:20j, 0:1:20j]
    U, V = np.zeros_like(X), np.zeros_like(Y)
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            U[i,j], V[i,j] = expected_vector_field(0, [X[i,j], Y[i,j]], game)

    # 3. Plotting
    plt.figure(figsize=(10, 8))
    plt.title("MARL Analysis via Ljung's ODE Method: Matching Pennies", fontsize=14)
    plt.xlabel("Probability Player A plays Action 0 ($x$)", fontsize=12)
    plt.ylabel("Probability Player B plays Action 0 ($y$)", fontsize=12)

    # Plot Vector Field
    plt.streamplot(X, Y, U, V, color='lightgray', density=1.5, arrowsize=1.5)

    # Plot Continuous ODE Trajectory
    plt.plot(ode_solution.y[0], ode_solution.y[1], 'b-', linewidth=2, label="Deterministic ODE $\dot{\\theta} = \\bar{h}(\\theta)$")

    # Plot Multiple Discrete Stochastic Trajectories
    for i in range(3):
        traj_x, traj_y = discrete_cross_learning(game, iterations=5000)
        # Only plot starting from same initial state for visual clarity on the main trajectory
        if i == 0:
             traj_x[0], traj_y[0] = initial_state
        plt.plot(traj_x, traj_y, alpha=0.4, linewidth=1, label=f"Stochastic Algorithm (Run {i+1})" if i==0 else "")

    plt.plot(0.5, 0.5, 'ro', markersize=8, label='Nash Equilibrium / Critical Point')
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.legend(loc='upper right')
    plt.grid(True, linestyle='--', alpha=0.6)

    # Uncomment the following line to display the plot if running locally
    # plt.show()
    print("Code successfully executed. Vector field and trajectories computed.")

if __name__ == "__main__":
    run_analysis()